# Generated by Django 5.1.3 on 2024-11-18 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoiteam',
            old_name='task',
            new_name='text',
        ),
    ]
